from database import DatabaseInteractor

database = DatabaseInteractor()
database.initConnection()
print("-----------------------Broj po marci-----------------------")
database.printCarNumberPerType()
print("-----------------------Broj po lokaciji-----------------------")
database.printCarNumberPerCity()
print("-----------------------Broj po boji-----------------------")
database.printCarNumberPerColor()
print("-----------------------Rang lista top 30-----------------------")
database.printMostExpensiveCars(30, None)
print("-----------------------Rang lista top 30 Dzipova-----------------------")
database.printMostExpensiveCars(30, "Džip/SUV")
print("-----------------------Rang lista svih izmedju 2021. i 2022.-----------------------")
database.printRangListBetween20212022()
print("-----------------------Najveca kubikaza-----------------------")
database.najvecaKubikaza()
print("-----------------------Najveca snaga-----------------------")
database.najvecaSnaga()
print("-----------------------Najveca kilometraza-----------------------")
database.najvecaKilometraza()
database.closeConnection()
